[project]
name = "mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies =  ["pydantic-ai-slim>=1.0", "openai>=1.107", "mcp-use", "langchain-openai>=0.3"]
